# Generated by Django 2.0 on 2018-06-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=500)),
                ('Answer', models.CharField(max_length=500)),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chewa_app.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_easy', models.BooleanField()),
                ('is_hard', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chewa_app.Level'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chewa_app.Content'),
        ),
        migrations.AddField(
            model_name='content',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chewa_app.Language'),
        ),
    ]
