# Generated by Django 2.0 on 2018-06-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='song/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chewa_app.Answers')),
            ],
        ),
    ]
