# Generated by Django 2.0 on 2018-06-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easy',
            name='easy_or_hard',
            field=models.BooleanField(choices=[(True, 'Easy'), (False, 'Hard')], max_length=100),
        ),
    ]
