# Generated by Django 2.0 on 2018-06-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='question',
            field=models.CharField(max_length=150),
        ),
    ]
