# Generated by Django 2.0 on 2018-06-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
        migrations.AlterField(
            model_name='level',
            name='Easy',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='level',
            name='Hard',
            field=models.BooleanField(),
        ),
    ]
