# Generated by Django 2.0 on 2018-06-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0002_auto_20180607_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='Easy',
        ),
        migrations.RemoveField(
            model_name='level',
            name='Hard',
        ),
        migrations.AddField(
            model_name='level',
            name='easy',
            field=models.BooleanField(default=1, verbose_name='Easy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='hard',
            field=models.BooleanField(default=1, verbose_name='Hard'),
            preserve_default=False,
        ),
    ]
