# Generated by Django 2.0 on 2018-06-15 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0002_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio',
            field=models.FileField(null=True, upload_to='song/'),
        ),
        migrations.AddField(
            model_name='audio',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chewa_app.Language'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.ImageField(null=True, upload_to='chewa_img/'),
        ),
    ]
