# Generated by Django 2.0 on 2018-06-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0002_auto_20180607_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='Level',
            new_name='Easy',
        ),
    ]
