# Generated by Django 2.0 on 2018-06-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0003_auto_20180607_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='easy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='hard',
            field=models.BooleanField(default=True),
        ),
    ]
