# Generated by Django 2.0 on 2018-06-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0003_auto_20180615_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='language',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='name',
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio',
            field=models.FileField(null=True, upload_to='song/'),
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
