# Generated by Django 2.0 on 2018-06-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0003_auto_20180614_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='answer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='choice1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='choice2',
            field=models.CharField(max_length=150),
        ),
    ]
