# Generated by Django 2.0 on 2018-06-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0003_auto_20180614_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
        migrations.AddField(
            model_name='profile',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
