# Generated by Django 2.0 on 2018-06-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0004_auto_20180615_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chewa_app.Answers'),
        ),
    ]
