# Generated by Django 2.0 on 2018-06-14 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0004_auto_20180614_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
