# Generated by Django 2.0 on 2018-06-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0004_auto_20180616_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
