# Generated by Django 2.0 on 2018-06-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0004_auto_20180607_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='easy',
        ),
        migrations.RemoveField(
            model_name='level',
            name='hard',
        ),
    ]
