# Generated by Django 2.0 on 2018-06-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0005_auto_20180607_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='easy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='level',
            name='hard',
            field=models.BooleanField(default=True),
        ),
    ]
