# Generated by Django 2.0 on 2018-06-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0006_auto_20180607_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='easy',
        ),
        migrations.RemoveField(
            model_name='level',
            name='hard',
        ),
        migrations.AddField(
            model_name='level',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
