# Generated by Django 2.0 on 2018-06-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewa_app', '0007_auto_20180607_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=30),
        ),
    ]
