# Generated by Django 2.0 on 2018-06-10 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chewa_app', '0009_auto_20180608_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='score',
            field=models.ManyToManyField(blank=True, related_name='answer_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
